--ROLLBACK
----------
-- DROP TABLE MELDING;
-- DROP SEQUENCE MELDING_ID_SEQ;
----------
--ROLLBACK

CREATE SEQUENCE MELDING_ID_SEQ
  START WITH 1
  INCREMENT BY 1;

CREATE TABLE MELDING (
  id         NUMBER              NOT NULL PRIMARY KEY,
  melding_id VARCHAR(255) UNIQUE NOT NULL,
  type       VARCHAR(255)        NOT NULL,
  registrert TIMESTAMP           NOT NULL
);