apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{app}}
  namespace: helsearbeidsgiver
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 600
      backoffLimit: 1
      template:
        spec:
          containers:
            - name: {{app}}
              image: {{image}}:{{tag}}
              resources:
                requests:
                  memory: 256Mi
                  cpu: 100m
                limits:
                  memory: 512Mi
                  cpu: 200m
              volumeMounts:
                - mountPath: /var/run/secrets/nais.io/vault
                  name: vault-secrets
                  subPath: subpath/var/run/secrets/nais.io/vault
              env:
                - name: VAULT_TOKEN_PATH
                  value: /var/run/secrets/nais.io/vault/vault_token
                - name: CRON_JOB_MODE
                  value: "true"
                - name: DATABASE_HOST
                  value: b27dbvl009.preprod.local
                - name: DATABASE_PORT
                  value: "5432"
                - name: DATABASE_NAME
                  value: syfoinntektsmelding
                - name: VAULT_MOUNTPATH
                  value: postgresql/preprod-fss/
                - name: HTTP_PROXY
                  value: http://webproxy.nais:8088
                - name: http_proxy
                  value: http://webproxy.nais:8088
                - name: HTTPS_PROXY
                  value: http://webproxy.nais:8088
                - name: https_proxy
                  value: http://webproxy.nais:8088
                - name: NO_PROXY
                  value: localhost,127.0.0.1,10.254.0.1,.local,.adeo.no,.nav.no,.aetat.no,.devillo.no,.oera.no,.nais.io
                - name: no_proxy
                  value: localhost,127.0.0.1,10.254.0.1,.local,.adeo.no,.nav.no,.aetat.no,.devillo.no,.oera.no,.nais.io
                - name: JAVA_PROXY_OPTIONS
                  value: "-Dhttp.proxyHost=webproxy.nais -Dhttps.proxyHost=webproxy.nais -Dhttp.proxyPort=8088 -Dhttps.proxyPort=8088 -Dhttp.nonProxyHosts=localhost|127.0.0.1|10.254.0.1|*.local|*.adeo.no|*.nav.no|*.aetat.no|*.devillo.no|*.oera.no|*.nais.io"
          imagePullSecrets:
            - name: gpr-credentials
          initContainers:
            - name: vks-init
              image: navikt/vault-sidekick:v0.3.10-d122b16
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "100m"
                limits:
                  memory: "128Mi"
                  cpu: "1000m"
              volumeMounts:
                - mountPath: /var/run/secrets/nais.io/vault
                  name: vault-secrets
                  subPath: subpath/var/run/secrets/nais.io/vault
              args:
                - -v=10
                - -logtostderr
                - -vault=https://vault.adeo.no
                - -one-shot
                - -save-token=/var/run/secrets/nais.io/vault/vault_token
                - -cn=secret:kv/preprod/fss/{{app}}/helsearbeidsgiver:dir=/var/run/secrets/nais.io/vault,fmt=flatten,retries=1
              env:
                - name: VAULT_AUTH_METHOD
                  value: kubernetes
                - name: VAULT_SIDEKICK_ROLE
                  value: {{app}}
                - name: VAULT_K8S_LOGIN_PATH
                  value: auth/kubernetes/preprod/fss/login
          serviceAccount: podcreator
          serviceAccountName: podcreator
          volumes:
            - name: vault-secrets
              emptyDir:
                medium: Memory
            - name: ca-bundle
              configMap:
                defaultMode: 420
                name: ca-bundle-jks
          restartPolicy: Never

