//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.16 at 10:36:23 a.m. CEST 
//


package no.nav.melding.virksomhet.dokumentnotifikasjon.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Forsendelsesinformasjon complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Forsendelsesinformasjon">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="arkivId" type="{http://nav.no/melding/virksomhet/dokumentnotifikasjon/v1}Identifikator"/>
 *         &lt;element name="arkivsystem" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tema" type="{http://nav.no/melding/virksomhet/dokumentnotifikasjon/v1}Tema"/>
 *         &lt;element name="behandlingstema" type="{http://nav.no/melding/virksomhet/dokumentnotifikasjon/v1}Behandlingstema" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Forsendelsesinformasjon", propOrder = {
    "arkivId",
    "arkivsystem",
    "tema",
    "behandlingstema"
})
public class XMLForsendelsesinformasjon {

    @XmlElement(required = true)
    protected String arkivId;
    @XmlElement(required = true)
    protected String arkivsystem;
    @XmlElement(required = true)
    protected XMLTema tema;
    protected XMLBehandlingstema behandlingstema;

    /**
     * Default no-arg constructor
     * 
     */
    public XMLForsendelsesinformasjon() {
        super();
    }

    /**
     * Fully-initialising value constructor
     * 
     */
    public XMLForsendelsesinformasjon(final String arkivId, final String arkivsystem, final XMLTema tema, final XMLBehandlingstema behandlingstema) {
        this.arkivId = arkivId;
        this.arkivsystem = arkivsystem;
        this.tema = tema;
        this.behandlingstema = behandlingstema;
    }

    /**
     * Gets the value of the arkivId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArkivId() {
        return arkivId;
    }

    /**
     * Sets the value of the arkivId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArkivId(String value) {
        this.arkivId = value;
    }

    /**
     * Gets the value of the arkivsystem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArkivsystem() {
        return arkivsystem;
    }

    /**
     * Sets the value of the arkivsystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArkivsystem(String value) {
        this.arkivsystem = value;
    }

    /**
     * Gets the value of the tema property.
     * 
     * @return
     *     possible object is
     *     {@link XMLTema }
     *     
     */
    public XMLTema getTema() {
        return tema;
    }

    /**
     * Sets the value of the tema property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLTema }
     *     
     */
    public void setTema(XMLTema value) {
        this.tema = value;
    }

    /**
     * Gets the value of the behandlingstema property.
     * 
     * @return
     *     possible object is
     *     {@link XMLBehandlingstema }
     *     
     */
    public XMLBehandlingstema getBehandlingstema() {
        return behandlingstema;
    }

    /**
     * Sets the value of the behandlingstema property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLBehandlingstema }
     *     
     */
    public void setBehandlingstema(XMLBehandlingstema value) {
        this.behandlingstema = value;
    }

    public XMLForsendelsesinformasjon withArkivId(String value) {
        setArkivId(value);
        return this;
    }

    public XMLForsendelsesinformasjon withArkivsystem(String value) {
        setArkivsystem(value);
        return this;
    }

    public XMLForsendelsesinformasjon withTema(XMLTema value) {
        setTema(value);
        return this;
    }

    public XMLForsendelsesinformasjon withBehandlingstema(XMLBehandlingstema value) {
        setBehandlingstema(value);
        return this;
    }

}
