CREATE TABLE SYKMELDING_DOK (
  SYKMELDING_DOK_ID NUMBER(19) not null primary key,
  AKTOR_ID VARCHAR2(20),
  ORGNUMMER VARCHAR2(20),
);

CREATE TABLE SYKEPENGESOEKNAD (
  SYKEPENGESOEKNAD_ID   NUMBER(19)       NOT NULL
    PRIMARY KEY,
  SYKEPENGESOEKNAD_UUID VARCHAR2(100)    NOT NULL
    UNIQUE,
  STATUS                VARCHAR2(100)    NOT NULL,
  SAKS_ID               VARCHAR2(20),
  JOURNALPOST_ID        VARCHAR2(20),
  FOM                   DATE,
  TOM                   DATE,
  SYKMELDING_DOK_ID NUMBER(19)
    constraint SYKEPENGESOEKNAD_SYK_DOK_FK
    references SYKMELDING_DOK,
);
