INSERT INTO SYKEPENGESOEKNAD (SYKEPENGESOEKNAD_ID, SYKEPENGESOEKNAD_UUID, OPPRETTET_DATO , STATUS, BEKREFTET_OPPLYSNINGSPLIKT, BEKREFTET_KORREKT_INFO, SAKS_ID, JOURNALPOST_ID, OPPGAVE_ID, DEL)
VALUES (1, 'uuid', DATE '2018-01-01', 'status', 1, 1, 'saksid', 'journalpostid', 'oppgaveid', 1);
