create table SYKMELDING_DOK (
  SYKMELDING_DOK_ID NUMBER(19) not null primary key,
  AKTOR_ID VARCHAR2(20),
  MELDING_ID VARCHAR2(100) not null unique,
  DOKUMENT CLOB not null,
  CREATED TIMESTAMP(6) not null,
  ARBEIDSSITUASJON VARCHAR2(100),
  SYKETILFELLE_START_DATO DATE,
  UNNTATT_INNSYN CHAR check (unntatt_innsyn IN (0, 1)),
  OPPFOLGINGSBEHOV CHAR check (oppfolgingsbehov IN (0, 1)),
  STATUS VARCHAR2(100) not null,
  ORGNUMMER VARCHAR2(20),
  SENDT_TIL_ARBEIDSGIVER_DATO DATE,
  BEHANDLET_DATO DATE,
  OPPFOELGING CHAR check (oppfoelging IN (0, 1)),
  MOTTAK_ID VARCHAR2(100) not null unique
)
