//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.16 at 10:36:23 a.m. CEST 
//


package no.nav.melding.virksomhet.dokumentnotifikasjon.v1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the no.nav.melding.virksomhet.dokumentnotifikasjon.v1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Forsendelsesinformasjon_QNAME = new QName("http://nav.no/melding/virksomhet/dokumentnotifikasjon/v1", "forsendelsesinformasjon");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: no.nav.melding.virksomhet.dokumentnotifikasjon.v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XMLForsendelsesinformasjon }
     * 
     */
    public XMLForsendelsesinformasjon createXMLForsendelsesinformasjon() {
        return new XMLForsendelsesinformasjon();
    }

    /**
     * Create an instance of {@link XMLBehandlingstema }
     * 
     */
    public XMLBehandlingstema createXMLBehandlingstema() {
        return new XMLBehandlingstema();
    }

    /**
     * Create an instance of {@link XMLKodeverdi }
     * 
     */
    public XMLKodeverdi createXMLKodeverdi() {
        return new XMLKodeverdi();
    }

    /**
     * Create an instance of {@link XMLTema }
     * 
     */
    public XMLTema createXMLTema() {
        return new XMLTema();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLForsendelsesinformasjon }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nav.no/melding/virksomhet/dokumentnotifikasjon/v1", name = "forsendelsesinformasjon")
    public JAXBElement<XMLForsendelsesinformasjon> createForsendelsesinformasjon(XMLForsendelsesinformasjon value) {
        return new JAXBElement<XMLForsendelsesinformasjon>(_Forsendelsesinformasjon_QNAME, XMLForsendelsesinformasjon.class, null, value);
    }

}
