//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.16 at 10:36:23 a.m. CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://nav.no/melding/virksomhet/dokumentnotifikasjon/v1")
package no.nav.melding.virksomhet.dokumentnotifikasjon.v1;
