//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.16 at 10:36:23 a.m. CEST 
//


package no.nav.melding.virksomhet.dokumentnotifikasjon.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Kodeverk for behandlingstema
 * 
 * <p>Java class for Behandlingstema complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Behandlingstema">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://nav.no/melding/virksomhet/dokumentnotifikasjon/v1>Kodeverdi">
 *       &lt;attribute name="kodeverksRef" type="{http://www.w3.org/2001/XMLSchema}anyURI" default="http://nav.no/kodeverk/Kodeverk/Behandlingstema" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Behandlingstema")
public class XMLBehandlingstema
    extends XMLKodeverdi
{

    @XmlAttribute(name = "kodeverksRef")
    @XmlSchemaType(name = "anyURI")
    protected String kodeverksRef;

    /**
     * Default no-arg constructor
     * 
     */
    public XMLBehandlingstema() {
        super();
    }

    /**
     * Fully-initialising value constructor
     * 
     */
    public XMLBehandlingstema(final String value, final String kodeRef, final String kodeverksRef) {
        super(value, kodeRef);
        this.kodeverksRef = kodeverksRef;
    }

    /**
     * Gets the value of the kodeverksRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKodeverksRef() {
        if (kodeverksRef == null) {
            return "http://nav.no/kodeverk/Kodeverk/Behandlingstema";
        } else {
            return kodeverksRef;
        }
    }

    /**
     * Sets the value of the kodeverksRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKodeverksRef(String value) {
        this.kodeverksRef = value;
    }

    public XMLBehandlingstema withKodeverksRef(String value) {
        setKodeverksRef(value);
        return this;
    }

    @Override
    public XMLBehandlingstema withValue(String value) {
        setValue(value);
        return this;
    }

    @Override
    public XMLBehandlingstema withKodeRef(String value) {
        setKodeRef(value);
        return this;
    }

}
