create table INNTEKTSMELDING (
   INNTEKTSMELDING_UUID VARCHAR2(100) NOT NULL PRIMARY KEY,
   AKTOR_ID VARCHAR2(50) NOT NULL,
   ORGNUMMER VARCHAR2(50) NOT NULL,
   ARBEIDSGIVERPERIODE_FOM DATE NOT NULL,
   ARBEIDSGIVERPERIODE_TOM DATE NOT NULL,
   SAK_ID VARCHAR2(50) NOT NULL
)
