create table INNTEKTSMELDING
(
	INNTEKTSMELDING_UUID VARCHAR(100) not null primary key,
	AKTOR_ID VARCHAR(50) not null,
	ORGNUMMER VARCHAR(50),
	SAK_ID VARCHAR(50) not null,
	JOURNALPOST_ID VARCHAR(100),
	BEHANDLET TIMESTAMP(6),
	ARBEIDSGIVER_PRIVAT VARCHAR(50)
);

create table ARBEIDSGIVERPERIODE
(
	PERIODE_UUID VARCHAR(100) not null primary key,
	INNTEKTSMELDING_UUID VARCHAR(100) not null,
	FOM DATE not null,
	TOM DATE not null,
	CONSTRAINT PERIODE_SOKNAD_ID_FK FOREIGN KEY (INNTEKTSMELDING_UUID) REFERENCES INNTEKTSMELDING (INNTEKTSMELDING_UUID)
);

