create table INNTEKTSMELDING (
    INNTEKTSMELDING_UUID VARCHAR(100) NOT NULL PRIMARY KEY,
    AKTOR_ID VARCHAR(50) NOT NULL,
    ORGNUMMER VARCHAR(50) NOT NULL,
    ARBEIDSGIVERPERIODE_FOM DATE NOT NULL,
    ARBEIDSGIVERPERIODE_TOM DATE NOT NULL,
    SAK_ID VARCHAR(50) NOT NULL
);
