CREATE TABLE ARBEIDSGIVERPERIODE (
    PERIODE_UUID         VARCHAR(100) NOT NULL PRIMARY KEY,
    INNTEKTSMELDING_UUID VARCHAR(100),
    FOM                  DATE          NOT NULL,
    TOM                  DATE          NOT NULL,
    CONSTRAINT PERIODE_SOKNAD_ID_FK FOREIGN KEY (INNTEKTSMELDING_UUID) REFERENCES INNTEKTSMELDING (INNTEKTSMELDING_UUID)
);

ALTER TABLE INNTEKTSMELDING ALTER COLUMN ARBEIDSGIVERPERIODE_FOM DROP NOT NULL;
ALTER TABLE INNTEKTSMELDING ALTER COLUMN ARBEIDSGIVERPERIODE_TOM DROP NOT NULL;


