CREATE TABLE ARBEIDSGIVERPERIODE (
  PERIODE_UUID         VARCHAR2(100) NOT NULL PRIMARY KEY,
  INNTEKTSMELDING_UUID VARCHAR2(100),
  FOM                  DATE          NOT NULL,
  TOM                  DATE          NOT NULL,

  CONSTRAINT PERIODE_SOKNAD_ID_FK FOREIGN KEY (INNTEKTSMELDING_UUID) REFERENCES INNTEKTSMELDING (INNTEKTSMELDING_UUID)
);

ALTER TABLE INNTEKTSMELDING MODIFY ARBEIDSGIVERPERIODE_FOM DATE NULL;
ALTER TABLE INNTEKTSMELDING MODIFY ARBEIDSGIVERPERIODE_TOM DATE NULL;







