INSERT INTO ARBEIDSGIVERPERIODE (PERIODE_UUID, INNTEKTSMELDING_UUID, FOM, TOM)
 SELECT
   uuid_in(md5(random()::text || clock_timestamp()::text)::cstring),
   INNTEKTSMELDING_UUID,
   ARBEIDSGIVERPERIODE_FOM,
   ARBEIDSGIVERPERIODE_TOM
 FROM INNTEKTSMELDING
 WHERE ARBEIDSGIVERPERIODE_FOM IS NOT NULL
       AND ARBEIDSGIVERPERIODE_TOM IS NOT NULL;
