package no.nav.syfo.domain.inntektsmelding

enum class Naturalytelse {
    KOSTDOEGN,
    LOSJI,
    ANNET,
    SKATTEPLIKTIGDELFORSIKRINGER,
    BIL,
    KOSTDAGER,
    RENTEFORDELLAAN,
    BOLIG,
    ELEKTRONISKKOMMUNIKASJON,
    AKSJERGRUNNFONDSBEVISTILUNDERKURS,
    OPSJONER,
    KOSTBESPARELSEIHJEMMET,
    FRITRANSPORT,
    BEDRIFTSBARNEHAGEPLASS,
    TILSKUDDBARNEHAGEPLASS,
    BESOEKSREISERHJEMMETANNET,
    INNBETALINGTILUTENLANDSKPENSJONSORDNING,
    YRKEBILTJENESTLIGBEHOVLISTEPRIS,
    YRKEBILTJENESTLIGBEHOVKILOMETER,
}
